### ISSUE TITLE
Incorrect Syntax

### ISSUE THREAD

**Issue by JuanPabloPearce** [cedwards4038/adguard-whitelist#1]
Looks like there is a case of incorrect syntax here. In order to whitelist a double @@ should be used.

`@@||www.redditmedia.com`

So this "whitelist" is actually blocking each entry since it is missing the @@

Another issue is the way the comments were made in the file. At the beginning `! text here` is used correctly. The line starting with ! is treated as a comment. Instead of using `!` for all other comments, a `#` is used. That symbol is not treated as a comment so it tries to filter out the following

`# Compiled by Charles Edwards`

**Comment by cedwards4038** [comment]
I’ll work on fixing this. I’ve been using it on AdGuard Home, which accepts either ! or #, and it’s been working very well.
![IMG_3382](https://github.com/cedwards4038/adguard-whitelist/assets/71619551/0bbd802c-3a0c-4221-a319-f57fbd3d57dd)

**Comment by JuanPabloPearce** [comment]
Ah that would be why. I use Adguard DNS and/or the Adguard client. I am actually modifying it now to reflect these changes. Pull request incoming <3

**Comment by cedwards4038** [comment]
I think this should be working now. I'm not sure about the REGEX rules though. 

I'm not sure if Adguard home will break this and do the opposite though. If this does that I'll raise an issue over there.

**Comment by cedwards4038** [comment]
Merged
